markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: BJT
url: http://bjt.name
subscribe: http://ztpala.com/feed.xml
exclude: [ README.md, newpost.rb ]
domain: bjt.name
author: Fengz
aotu: true
email: enjoyforfun+blog@gmail.com
twitterID: ycf
duoshuoShortname: sync